Repository apache/incubator-hugegraph-doc, pull requests merged in 2023-12, with the labels that each got.

#312 doc(release-note): computer release note 1.2.0
  content/en/docs/changelog/hugegraph-1.2.0-release-notes.md
Labels: size:M, lgtm

#311 doc: update toolchain release-note 1.2.0
  content/en/docs/changelog/hugegraph-1.2.0-release-notes.md
Labels: size:L, lgtm

#314 doc(release-note): commons and server release note 1.2.0
  content/en/docs/changelog/hugegraph-1.2.0-release-notes.md
Labels: size:L, lgtm

#313 doc(release-note): computer release note 1.2.0
  content/en/docs/changelog/hugegraph-1.2.0-release-notes.md
Labels: size:M, lgtm

#310 fix: double quotes to avoid spaces in grep for validating release
  .github/workflows/validate-release.yml
  dist/validate-release.sh
Labels: size:S, lgtm

#315 refact: enhance the validate-release format
  content/cn/docs/contribution-guidelines/validate-release.md
  content/en/docs/contribution-guidelines/validate-release.md
Labels: size:L

#317 doc(quickstart): computer claim jdk11
  content/en/docs/quickstart/hugegraph-computer.md
Labels: enhancement, size:M

#318 Update download.md
  content/cn/docs/download/download.md
  content/cn/docs/quickstart/hugegraph-server.md
  content/en/docs/download/download.md
  content/en/docs/quickstart/hugegraph-server.md
Labels: enhancement, size:M
