Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-02, with the labels that each got.

#324 doc: sync doc about enable auth for docker image
  content/cn/_index.html
  content/cn/docs/changelog/_index.md
  content/cn/docs/changelog/hugegraph-0.10.4-release-notes.md
  content/cn/docs/changelog/hugegraph-0.11.2-release-notes.md
  content/cn/docs/changelog/hugegraph-0.12.0-release-notes.md
  content/cn/docs/changelog/hugegraph-0.2-release-notes.md
  content/cn/docs/changelog/hugegraph-0.2.4-release-notes.md
  content/cn/docs/changelog/hugegraph-0.3.3-release-notes.md
  content/cn/docs/changelog/hugegraph-0.4.4-release-notes.md
  content/cn/docs/changelog/hugegraph-0.5.6-release-notes.md
  content/cn/docs/changelog/hugegraph-0.6.1-release-notes.md
  content/cn/docs/changelog/hugegraph-0.7.4-release-notes.md
  content/cn/docs/changelog/hugegraph-0.8.0-release-notes.md
  content/cn/docs/changelog/hugegraph-0.9.2-release-notes.md
  content/cn/docs/changelog/hugegraph-1.0.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.2.0-release-notes.md
  content/cn/docs/config/config-authentication.md
  content/cn/docs/config/config-computer.md
  content/cn/docs/config/config-guide.md
  content/cn/docs/config/config-https.md
  content/cn/docs/config/config-option.md
  content/cn/docs/guides/architectural.md
  content/cn/docs/guides/backup-restore.md
  content/cn/docs/guides/desgin-concept.md
  content/cn/docs/images/images-server/31docker-option.jpg
  content/cn/docs/performance/api-preformance/_index.md
  content/cn/docs/performance/hugegraph-benchmark-0.5.6.md
  content/cn/docs/performance/hugegraph-loader-performance.md
  content/cn/docs/quickstart/hugegraph-client.md
  content/cn/docs/quickstart/hugegraph-computer.md
  content/cn/docs/quickstart/hugegraph-hubble.md
  content/cn/docs/quickstart/hugegraph-loader.md
  content/cn/docs/quickstart/hugegraph-server.md
  content/cn/docs/quickstart/hugegraph-tools.md
  content/en/docs/changelog/hugegraph-0.10.4-release-notes.md
  content/en/docs/changelog/hugegraph-0.11.2-release-notes.md
  content/en/docs/changelog/hugegraph-0.12.0-release-notes.md
  content/en/docs/changelog/hugegraph-0.2-release-notes.md
  content/en/docs/changelog/hugegraph-0.2.4-release-notes.md
  content/en/docs/changelog/hugegraph-0.3.3-release-notes.md
  content/en/docs/changelog/hugegraph-0.4.4-release-notes.md
  content/en/docs/changelog/hugegraph-0.5.6-release-notes.md
  content/en/docs/changelog/hugegraph-0.6.1-release-notes.md
  content/en/docs/changelog/hugegraph-0.7.4-release-notes.md
  content/en/docs/changelog/hugegraph-0.8.0-release-notes.md
  content/en/docs/changelog/hugegraph-0.9.2-release-notes.md
  content/en/docs/changelog/hugegraph-1.0.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.2.0-release-notes.md
  content/en/docs/config/config-authentication.md
  content/en/docs/images/images-server/31docker-option.jpg
  content/en/docs/quickstart/hugegraph-client.md
  content/en/docs/quickstart/hugegraph-hubble.md
  content/en/docs/quickstart/hugegraph-loader.md
  content/en/docs/quickstart/hugegraph-server.md
Labels: enhancement, size:L, lgtm

#323 doc: add docs for committer guidelines
  README.md
  content/cn/docs/contribution-guidelines/committer-guidelines.md
  content/en/docs/contribution-guidelines/committer-guidelines.md
Labels: enhancement, size:XL, lgtm

#328 fix: guideline email title
  content/cn/docs/contribution-guidelines/committer-guidelines.md
  content/en/docs/contribution-guidelines/committer-guidelines.md
Labels: size:S, lgtm
