Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-04, with the labels that each got.

#345 doc:update download.md for release 1.3.0
  content/cn/docs/download/download.md
  content/cn/docs/quickstart/hugegraph-server.md
  content/en/docs/download/download.md
  content/en/docs/quickstart/hugegraph-server.md
Labels: enhancement, size:M, lgtm

#344 sec: enhance some desc for users
  content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md
  content/cn/docs/quickstart/hugegraph-client.md
  content/cn/docs/quickstart/hugegraph-hubble.md
  content/cn/docs/quickstart/hugegraph-server.md
  content/en/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/en/docs/contribution-guidelines/hugegraph-server-idea-setup.md
  content/en/docs/quickstart/hugegraph-client.md
  content/en/docs/quickstart/hugegraph-hubble.md
  content/en/docs/quickstart/hugegraph-server.md
Labels: enhancement, size:L, lgtm

#347 doc: fix doc link 404
  content/cn/docs/quickstart/hugegraph-server.md
Labels: bug, size:XS, lgtm

#348 chore: update 1.3.0 cn download page
  content/cn/docs/download/download.md
  content/en/docs/download/download.md
Labels: enhancement, size:M, lgtm

#349 chore: improve 1.3.0 download page
  content/cn/docs/download/download.md
  content/en/docs/download/download.md
Labels: enhancement, size:L, lgtm

#350 fix: download page inconsistent link between artifacts and sha512 files
  content/cn/docs/download/download.md
  content/en/docs/download/download.md
Labels: bug, size:M, lgtm

#351 fix: rename http to https in download page
  content/cn/docs/download/download.md
  content/en/docs/download/download.md
Labels: bug, size:M, lgtm

#353 fix: enhance the code reading experience for lacking RPC generated files
  content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md
  content/en/docs/contribution-guidelines/hugegraph-server-idea-setup.md
Labels: enhancement, size:S, lgtm

#354 chore: improve docs for gremlin console
  content/cn/docs/clients/gremlin-console.md
  content/en/docs/clients/gremlin-console.md
Labels: enhancement, size:L, lgtm

#358 refact: add 3 SEC issues & enhance the intro/perf doc
  .editorconfig
  README.md
  content/cn/docs/guides/security.md
  content/cn/docs/introduction/README.md
  content/cn/docs/performance/api-preformance/hugegraph-api-0.5.6-Cassandra.md
  content/cn/docs/performance/api-preformance/hugegraph-api-0.5.6-RocksDB.md
  content/cn/docs/performance/hugegraph-benchmark-0.5.6.md
  content/cn/docs/performance/hugegraph-loader-performance.md
  content/cn/docs/quickstart/hugegraph-ai.md
  content/en/docs/guides/security.md
  content/en/docs/introduction/README.md
  content/en/docs/performance/api-preformance/hugegraph-api-0.5.6-Cassandra.md
  content/en/docs/performance/api-preformance/hugegraph-api-0.5.6-RocksDB.md
  content/en/docs/performance/hugegraph-benchmark-0.5.6.md
  content/en/docs/performance/hugegraph-loader-performance.md
  content/en/docs/quickstart/hugegraph-ai.md
Labels: enhancement, size:XL, lgtm
