Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-08, with the labels that each got.

#368 refine rest-server.property documentation
  content/cn/docs/config/config-guide.md
  content/en/docs/config/config-guide.md
Labels: size:S, lgtm

#366 doc: update "How to Contribute" link and delete redundant "Guildlines"
  README.md
Labels: size:XS, lgtm

#365 fix: translation correction.
  content/en/docs/quickstart/hugegraph-hubble.md
Labels: size:XS, lgtm

#369 fix: svg styles interfering with each other
  themes/docsy/assets/icons/logo.svg
  themes/docsy/layouts/partials/footer.html
Labels: bug, size:XS, lgtm
