Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-12, with the labels that each got.

#381 fix: update image desc for all modules
  content/cn/docs/config/config-authentication.md
  content/cn/docs/contribution-guidelines/validate-release.md
  content/cn/docs/quickstart/hugegraph-hubble.md
  content/cn/docs/quickstart/hugegraph-loader.md
  content/cn/docs/quickstart/hugegraph-server.md
  content/en/docs/config/config-authentication.md
  content/en/docs/contribution-guidelines/validate-release.md
  content/en/docs/quickstart/hugegraph-hubble.md
  content/en/docs/quickstart/hugegraph-loader.md
  content/en/docs/quickstart/hugegraph-server.md
Labels: size:M

#379 chore(dist): update validate release scripts for releasing 1.5.0
  .github/workflows/validate-release.yml
  dist/validate-release.sh
Labels: size:M, lgtm

#382 docs: update download.md for release 1.5.0
  content/cn/docs/download/download.md
  content/en/docs/download/download.md
Labels: size:M, lgtm

#385 chore: update version to 1.5.0
  content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.5.0-release-notes.md
  content/cn/docs/config/config-authentication.md
  content/cn/docs/quickstart/hugegraph-client.md
  content/cn/docs/quickstart/hugegraph-hubble.md
  content/cn/docs/quickstart/hugegraph-loader.md
  content/cn/docs/quickstart/hugegraph-server.md
  content/en/docs/config/config-authentication.md
  content/en/docs/introduction/README.md
  content/en/docs/quickstart/hugegraph-ai.md
  content/en/docs/quickstart/hugegraph-client.md
  content/en/docs/quickstart/hugegraph-computer.md
  content/en/docs/quickstart/hugegraph-hubble.md
  content/en/docs/quickstart/hugegraph-loader.md
  content/en/docs/quickstart/hugegraph-server.md
Labels: size:L

#383 doc: update hugegraph-1.5.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.5.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.5.0-release-notes.md
Labels: size:L, lgtm
