Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-11, with the labels that each got.

#376 doc: add JVM(in-heap) memory monitor config desc
  content/cn/docs/config/config-guide.md
  content/cn/docs/config/config-option.md
  content/en/docs/config/config-guide.md
  content/en/docs/config/config-option.md
Labels: enhancement, size:L, lgtm

#375 doc(ai): sync/merge the ai documentation with README
  content/cn/docs/quickstart/hugegraph-ai.md
  content/en/docs/images/gradio-kg.png
  content/en/docs/quickstart/hugegraph-ai.md
Labels: size:XL, lgtm

#378 docs(hg-ai): fix img link
  content/cn/docs/images/gradio-kg.png
  content/cn/docs/quickstart/hugegraph-ai.md
  content/en/docs/quickstart/hugegraph-ai.md
Labels: size:XS, lgtm

#380 doc: update 1.5.0 release notes
  content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.5.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.5.0-release-notes.md
Labels: size:M, lgtm
