Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-05, with the labels that each got.

#342 fix: validate-release.sh for 1.3.0
  dist/validate-release.sh
Labels: bug, size:S, lgtm

#360 fix: incubation disclaimer in every page
  content/cn/_index.html
  content/en/_index.html
  themes/docsy/assets/icons/apache-incubator.svg
  themes/docsy/layouts/partials/footer.html
Labels: size:S, lgtm

#333 doc(hubble): enhance hubble usage doc/command
  content/cn/docs/quickstart/hugegraph-hubble.md
  content/en/docs/quickstart/hugegraph-hubble.md
Labels: enhancement, inactive, size:M, lgtm
