Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-09, with the labels that each got.

#370 fix: misleading in dynamic crate graph api
  content/cn/docs/clients/restful-api/graphs.md
  content/en/docs/clients/restful-api/graphs.md
Labels: bug, size:M, lgtm

#372 Modify the text of data types of property-api
  content/cn/docs/clients/restful-api/propertykey.md
  content/en/docs/clients/restful-api/propertykey.md
Labels: size:XS, lgtm

#371 doc: update Scylladb integration faq
  content/en/docs/guides/faq.md
Labels: enhancement, size:XS, lgtm
