Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-03, with the labels that each got.

#332 doc: add security page and description
  content/cn/docs/guides/security.md
  content/en/docs/guides/security.md
  themes/docsy/layouts/partials/community_links.html
Labels: enhancement, size:M, lgtm

#331 doc: add hugegraph-ai doc
  README.md
  content/cn/docs/images/gradio-config.png
  content/cn/docs/images/gradio-kg.png
  content/cn/docs/images/gradio-rag-1.png
  content/cn/docs/images/gradio-rag-2.png
  content/cn/docs/images/gradio-rag.png
  content/cn/docs/images/kg-uml.png
  content/cn/docs/quickstart/hugegraph-ai.md
  content/en/docs/images/gradio-config.png
  content/en/docs/images/gradio-kg.png
  content/en/docs/images/gradio-rag-1.png
  content/en/docs/images/gradio-rag-2.png
  content/en/docs/images/gradio-rag.png
  content/en/docs/images/kg-uml.png
  content/en/docs/quickstart/hugegraph-ai.md
Labels: enhancement, size:L, lgtm

#329 chore(dist): improve validate-release.sh
  dist/validate-release.sh
Labels: enhancement, size:L, lgtm

#330 chore(dist): add deploy-release.sh to download & start services
  dist/deploy-release.sh
Labels: enhancement, size:M, lgtm

#334 chore: disable ai mvn building
  .github/workflows/validate-release.yml
  README.md
  content/cn/docs/contribution-guidelines/committer-guidelines.md
  dist/validate-release.sh
Labels: bug, size:S, lgtm

#335 chore: create hugegraph-1.2.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.3.0-release-notes.md
Labels: enhancement, size:M, lgtm

#337 chore: update validate-release guide
  content/cn/docs/contribution-guidelines/validate-release.md
  content/en/docs/contribution-guidelines/validate-release.md
Labels: size:S, lgtm

#339 fix: a string of enhancement for the website/sec page
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  config.toml
  content/cn/docs/clients/restful-api/auth.md
  content/cn/docs/clients/restful-api/graphs.md
  content/cn/docs/config/config-authentication.md
  content/cn/docs/config/config-option.md
  content/cn/docs/introduction/README.md
  content/cn/docs/quickstart/hugegraph-hubble.md
  content/en/docs/clients/restful-api/graphs.md
  content/en/docs/config/config-authentication.md
  content/en/docs/config/config-option.md
  content/en/docs/introduction/README.md
  content/en/docs/quickstart/hugegraph-hubble.md
  content/en/docs/quickstart/hugegraph-server.md
  contribution.md
  themes/docsy/layouts/partials/community_links.html
Labels: enhancement, size:L, lgtm

#341 Update hugegraph-1.3.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md
Labels: enhancement, size:M, lgtm

#338 Update AI section in 1.3.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.3.0-release-notes.md
Labels: enhancement, size:M, lgtm

#340 refactor: enhance the weight & add server & commons notes
  content/cn/docs/changelog/hugegraph-0.12.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.0.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.2.0-release-notes.md
  content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.2.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.3.0-release-notes.md
Labels: enhancement, size:L, lgtm
