Repository apache/incubator-hugegraph-doc, pull requests merged in 2024-01, with the labels that each got.

#316 chore(doc): update hugegraph doc about install
  content/cn/docs/config/config-authentication.md
  content/cn/docs/quickstart/hugegraph-server.md
  content/en/docs/config/config-authentication.md
  content/en/docs/quickstart/hugegraph-server.md
Labels: enhancement, size:M

#320 chore(auth): update auth config doc for re-init
  content/cn/docs/config/config-authentication.md
  content/en/docs/config/config-authentication.md
Labels: size:XS, lgtm

#321 chore(release): modify the Java compatibility description.
  content/cn/docs/changelog/hugegraph-1.2.0-release-notes.md
  content/en/docs/changelog/hugegraph-1.2.0-release-notes.md
Labels: size:XS, lgtm

#325 fix: server quickstart swagger-ui image link
  content/cn/docs/images/images-server/swagger-ui-set-auth-example.png
  content/cn/docs/images/images-server/swagger-ui-where-set-auth-example.png
  content/cn/docs/images/images-server/swagger-ui.png
  content/cn/docs/quickstart/hugegraph-server.md
  content/en/docs/images/images-server/swagger-ui-set-auth-example.png
  content/en/docs/images/images-server/swagger-ui-where-set-auth-example.png
  content/en/docs/images/images-server/swagger-ui.png
  content/en/docs/quickstart/hugegraph-server.md
Labels: bug, size:S, lgtm

#326 doc(setup-idea): consider the scenario of configuring authenticator in Java 11 for server
  content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md
Labels: enhancement, size:M, lgtm

#327 doc(setup-idea): sync EN doc for previous PR
  content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md
  content/en/docs/contribution-guidelines/hugegraph-server-idea-setup.md
Labels: enhancement, size:M, lgtm
