Repository apache/incubator-hugegraph-doc, pull requests merged in 2025-02, with the labels that each got.

#374 doc(computer): add vermeer cn documentation in quickstart
  content/cn/docs/quickstart/hugegraph-vermeer.md
  content/en/docs/quickstart/hugegraph-hubble.md
Labels: enhancement, inactive, size:L, lgtm

#391 fix: critical CSP problem
  themes/docsy/layouts/_default/baseof.html
Labels: bug, size:XS, lgtm

#392 fix: enhance CSP rule
  themes/docsy/layouts/_default/baseof.html
Labels: enhancement, size:XS, lgtm

#393 fix: move csp rule
  themes/docsy/layouts/_default/baseof.html
  themes/docsy/layouts/partials/head.html
Labels: size:S, lgtm

#394 fix: csp inline
  themes/docsy/layouts/partials/head.html
Labels: size:XS, lgtm

#395 refactor: use local static files for ASF CSP rule
  themes/docsy/layouts/partials/head.html
  themes/docsy/layouts/partials/scripts.html
  themes/docsy/static/css/open-sans.css
  themes/docsy/static/css/rubik.css
  themes/docsy/static/css/tajawal.css
  themes/docsy/static/js/bootstrap.min.js
  themes/docsy/static/js/jquery.min.js
  themes/docsy/static/js/lunr.min.js
  themes/docsy/static/js/mermaid.min.js
  themes/docsy/static/js/popper.min.js
  themes/docsy/static/webfonts/open-sans/open-sans-v40-latin-300.woff2
  themes/docsy/static/webfonts/open-sans/open-sans-v40-latin-300italic.woff2
  themes/docsy/static/webfonts/open-sans/open-sans-v40-latin-700.woff2
  themes/docsy/static/webfonts/open-sans/open-sans-v40-latin-700italic.woff2
  themes/docsy/static/webfonts/open-sans/open-sans-v40-latin-italic.woff2
  themes/docsy/static/webfonts/open-sans/open-sans-v40-latin-regular.woff2
  themes/docsy/static/webfonts/rubik/rubik-v28-latin-300.woff2
  themes/docsy/static/webfonts/rubik/rubik-v28-latin-500.woff2
  themes/docsy/static/webfonts/rubik/rubik-v28-latin-600.woff2
  themes/docsy/static/webfonts/rubik/rubik-v28-latin-700.woff2
  themes/docsy/static/webfonts/rubik/rubik-v28-latin-regular.woff2
  themes/docsy/static/webfonts/tajawal/tajawal-v10-latin-300.woff2
  themes/docsy/static/webfonts/tajawal/tajawal-v10-latin-500.woff2
  themes/docsy/static/webfonts/tajawal/tajawal-v10-latin-700.woff2
  themes/docsy/static/webfonts/tajawal/tajawal-v10-latin-regular.woff2
Labels: size:L, lgtm

#396 doc: add EN for vermeer(OLAP) & server auth
  content/cn/docs/quickstart/hugegraph-server.md
  content/cn/docs/quickstart/hugegraph-spark.md
  content/cn/docs/quickstart/hugegraph-vermeer.md
  content/en/docs/quickstart/hugegraph-server.md
  content/en/docs/quickstart/hugegraph-vermeer.md
Labels: size:XL, lgtm
